# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55366ab89944704289538a63ca0ed2ea9f830d3505237d82b2aa6b08c6356a286da101ca9086b02081c42111054b03bcf29e1a9854cbafb290f84b220f8aad54

test:
  secret_key_base: 3c16bd244615a7dd22cd5c26955e19c89f8485d5048fbd4ba6936063a89a06a483ede1f5ad8fdab65f2c7c54ee5d6b33f73b126ea140f29f9550dc21f51f53c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
